/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const apply_lut: (a: number, b: number, c: any, d: number, e: number) => void;
export const blacks: (a: number, b: number, c: any, d: number) => void;
export const box_blur: (a: number, b: number, c: any, d: number, e: number, f: number) => void;
export const brightness: (a: number, b: number, c: any, d: number) => void;
export const clarity: (a: number, b: number, c: any, d: number, e: number, f: number) => void;
export const color_grade: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => void;
export const contrast: (a: number, b: number, c: any, d: number) => void;
export const dehaze: (a: number, b: number, c: any, d: number) => void;
export const edge_detect: (a: number, b: number, c: any, d: number, e: number, f: number) => void;
export const exposure: (a: number, b: number, c: any, d: number) => void;
export const grain: (a: number, b: number, c: any, d: number) => void;
export const grayscale: (a: number, b: number, c: any, d: number) => void;
export const highlights: (a: number, b: number, c: any, d: number) => void;
export const hsl_adjust: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number) => void;
export const hue_rotate: (a: number, b: number, c: any, d: number) => void;
export const invert: (a: number, b: number, c: any, d: number) => void;
export const saturation: (a: number, b: number, c: any, d: number) => void;
export const sepia: (a: number, b: number, c: any, d: number) => void;
export const shadows: (a: number, b: number, c: any, d: number) => void;
export const sharpen: (a: number, b: number, c: any, d: number, e: number, f: number) => void;
export const temperature: (a: number, b: number, c: any, d: number) => void;
export const threshold: (a: number, b: number, c: any, d: number) => void;
export const tint: (a: number, b: number, c: any, d: number) => void;
export const vignette: (a: number, b: number, c: any, d: number, e: number, f: number) => void;
export const whites: (a: number, b: number, c: any, d: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_start: () => void;
